### ISSUE TITLE
Interne Schnittstellen

### ISSUE THREAD

**Issue by tbollmeyer** [Software-Projekt-2022/Kultur#11]
**Definition** der internen Schnittstellen

**Comment by MaFi1504** [comment]
@tbollmeyer sind damit alle Schnittstellen der API gemeint?

**Comment by tbollmeyer** [comment]
Ja genau. Alle Endpunkte sollen mindestens definiert sein.
Für Endpunkte, die noch nicht implementiert sind, kann erstmal ein `501 Not implemented` zurückgegeben werden.

**Comment by MaFi1504** [comment]
Okay alles klar
